-
  name: Add host entries to hosts file for each server
  hosts: all
  tasks:
    -
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.140    dockansi.example.com    dockansi'
    -
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.141    web1.example.com    web1'
    -
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.142    db1.example.com    db1'
    -
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.131    tgt1.example.com    tgt1'
    -
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.132    tgt2.example.com    tgt2'