- hosts: web
  vars:
    dns_server: 192.168.33.100 #Fictional IP address
  tasks:
    - name: Print the output of /etc/hosts and store it in a variable
      shell: cat /etc/hosts
      register: hosts_file_contents
      
    - name: Use the DNS server if no entry for database server is found in the hosts file
      become: yes
      shell: 'echo nameserver "{{ dns_server }}" > /etc/resolv.conf'
      when: hosts_file_contents.stdout.find('192.168.33.30') == -1