- hosts: db
  vars:
    - dbpass: mypassword
    - newpass: adminpassword # The new password for root
  tasks:
    - name: Download and install mariadb
      yum: name={{ item }} state=present
      with_items:
        - mariadb-server
        - MySQL-python
      
    - block:
      - name: Configure the root password for mariadb
        mysql_user:
          name: root
          host: localhost
          password: '{{ newpass }}'
      rescue:
        - name: Change the root password if it is already set
          mysql_user:
            name: root
            host: localhost
            password: '{{ newpass }}'
            login_user: root
            login_password: '{{ dbpass }}'
      always:
        - name: Remove anonymous user accounts
          mysql_user:
            name: ''
            host_all: yes
            state: absent
            login_user: root
            login_password: '{{ newpass }}'