---
- hosts: all
  become: yes
  tasks: 
      - name: Install PHP 7 most common packages
        yum: name={{ item }} state=present
        with_items:
            - mod_php71w 
            - php71w-cli 
            - php71w-common 
            - php71w-gd 
            - php71w-mbstring 
            - php71w-mcrypt 
            - php71w-mysqlnd 
            - php71w-xml