---
- hosts: all
  become: yes
  tasks:
    - name: Install PHP 7 most common packages
      yum: name={{ item }} state=present
      loop:
        - mod_php
        - php-cli
        - php-common
        - php-gd
        - php-mbstring
        - php-mcrypt
        - php-mysqlnd
        - php-xml

