-
  name: 'Install httpd'
  hosts: target1
  become: yes
  tasks:
    -
        name: 'Install Apache'
        package:
          name: httpd
          state: present
    -
        name: 'Start httpd'
        service:
          name: httpd
          state: started
