---
# tasks file for appserver
- name: Ensure that Apache is installed
  yum: 
    name: httpd
    state: present
- name: Ensure that Apache is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes
- name: Install PHP 7 most common packages
  yum: name={{ item }} state=present        
  with_items:            
    - mod_php71w
    - php71w-cli
    - php71w-common
    - php71w-gd
    - php71w-mbstring
    - php71w-mcrypt
    - php71w-mysqlnd
    - php71w-xml
- name: Install Rsync
  yum: name=rsync state=present
- name: Deploy and configure CodeIgniter
  synchronize: 
      src: /vagrant/CodeIgniter-3.1.4/
      dest: /var/www/html/
- name: Ensure that mod_rewrite is enabled
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-base.conf 
    regexp: '^.*rewrite_module.*$'
    line: 'LoadModule rewrite_module modules/mod_rewrite.so'
    state: present
  notify: 
    - restart Apache
