---
- hosts: ftp
  become: true
  become_user: root
  tasks:
    - name: "Install vsftpd service."
      package:
        name: vsftpd
        state: present
    - name: "Start vsftpd service"
      service: name=vsftpd state=started enabled=yes
...