---
- hosts: db
  tasks:
    - name: Ansible Loop
      debug:
        msg: "{{ item }}"
      with_items:
        - "hello1"
        - "hello2"
        - "hello3"
        - "hello4"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int > 7
