---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Copy a file"
      copy:
        src: /tmp/xyz2
        dest: /tmp
        owner: jsantos
        group: root
        mode: '777'
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
...