---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "Copy a file"
      copy:
        src: /tmp/abcd
        dest: /tmp
        owner: jsantos
        group: root
        mode: '777'
...