---
- hosts: web
  become: true
  become_user: root
  tasks:
    - name: 'Check that Apache web service is uninstalled on all nodes'
      service: name=httpd.service state=stopped enabled=no
    - name: 'Uninstall Apache, if necessary'
      dnf: name=httpd state=absent
...