---
- hosts: web
  become: true
  become_user: root
  tasks:
    - name: 'Check that Apache web service is installed on nodes'
      dnf: name=httpd state=present
    - name: 'Start and enable Apache2'
      service: name=httpd.service state=started enabled=yes
...