---
- hosts: 192.168.11.31
  become: true
  become_user: root
  tasks:
    - name: 'Install Latest Apache Web service'
      package: 
        name: httpd
        state: latest
    - name: 'Start and enable Apache2'
      service: 
        name: httpd
        state: started
        enabled: yes
    - name: 'Open ports 80 and 443 on Firewall'
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: 'Create simple html page'
      copy:
        content: "Welcome to the Ansible Learning Course Module.\n"
        dest: /var/www/html/index.html
    - name: 'Defining Web Server Name'
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerName www.{{ ansible_nodename }}:80
        insertafter: "#ServerName"
    - name: 'Update Web Server Entry in /etc/hosts File'
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4['address'] }}  www.{{ ansible_nodename }}"
...