---
- hosts: rhel7
  become: true
  become_user: root
  tasks:
      - name: Unmount the OS Media Drive
        mount:
          path: /mnt
          src: /dev/sr0
          state: absent
        when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
      - name: Delete the Local Repo File
        file:
          path: /etc/yum.repos.d/rhel7dvd.repo
          state: absent
        when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
      - name: Stop & Disable the VSFTPD Service
        service:
          name: vsftpd
          state: stopped
          enabled: false
      - name: Stop & Disable the HTTPD Service
        service:
          name: httpd
          state: stopped
          enabled: false
      - name: Uninstall the VSFTPD Package
        yum: 
          name: vsftpd
          state: absent
      - name: Uninstall HTTPD Package
        yum:
          name: httpd
          state: absent
