---
- hosts: db
  become: true
  become_user: root
  tasks:
    - name: Print various Ansible Facts
      debug:
        msg: >
                The Default address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}